"""Regression tests for the ses-a6ddf3c8 (Eco.Calc) post-mortem fixes.

Covers:
1. Plan-gate Id-header rule — a plan that uses `CID_<X>` without ever
   naming `Id<X>.h` must be BLOCKED at to_coder (the missing Id include
   caused 3 failed build cycles + a 116 KB header read in a6ddf3c8).
2. read() oversized-marketplace-header hint (the 116 KB Id read that
   triggered mid-run history compression).
3. auto mode keeps the HITL plan gate (user decision 2026-09-08).
"""
from pathlib import Path
import json

from eco_harness.agent.internal.tools.plan_validator import (
    validate_closed_plan,
)
from eco_harness.agent.internal.tools.code_search import make_code_search_tools

# ── fixtures ────────────────────────────────────────────────────────────────
# The validator has many orthogonal rules (bootstrap, target triple, size);
# fixtures below intentionally satisfy the unrelated rules where possible,
# but assertions are scoped to the Id-header rule message so the tests stay
# focused even when other validators fire.


def _plan_with_register(cid_line: str) -> str:
    return f"""
## Target triple
Linux / x86_64 / StaticRelease (verbatim from seed)

## Bootstrap
EcoMain -> QueryInterface(GID_IEcoSystem) -> IEcoSystem1 ->
QueryInterface(IID_IEcoInterfaceBus1) -> IEcoInterfaceBus1.

## Capability mapping
{cid_line}
"""


# ── 1. plan gate: Id-header rule ────────────────────────────────────────────
def test_cid_symbol_without_id_header_is_blocked():
    plan = _plan_with_register(
        "RegisterComponent(pIBus, &CID_EcoFileSystemManagement1,"
        " (IEcoUnknown*)GetIEcoComponentFactoryPtr_00000000000000000000000046534D31);"
    )
    reasons = _id_rule_messages(plan)
    assert any("IdEcoFileSystemManagement1" in m for m in reasons), (
        "plan uses CID_EcoFileSystemManagement1 without naming its Id header — "
        "the gate must block (a6ddf3c8 bug history)"
    )


def _id_rule_messages(plan: str) -> list[str]:
    return [
        v.message for v in validate_closed_plan(plan)
        if v.severity == "block" and "ID header" in v.message
    ]


def test_cid_symbol_with_id_include_passes_id_rule():
    plan = _plan_with_register(
        "RegisterComponent(pIBus, &CID_EcoFileSystemManagement1,"
        " (IEcoUnknown*)GetIEcoComponentFactoryPtr_00000000000000000000000046534D31);"
        "\n\nInclude block: #include \"IdEcoFileSystemManagement1.h\""
    )
    assert not _id_rule_messages(plan)


def test_locally_authored_component_still_requires_id_include():
    """A generated local Id header must be visible in the entry translation
    unit just like a marketplace Id header."""
    plan = _plan_with_register(
        "RegisterComponent(pIBus, &CID_EcoMyNew1, my_factory);"
    ) + "\nSpec: docs/specs/EcoMyNew1.md\n"
    assert _id_rule_messages(plan)
    with_include = plan + '\n#include "IdEcoMyNew1.h"\n'
    assert not _id_rule_messages(with_include)


def test_bare_id_header_prose_does_not_pass_id_rule():
    plan = _plan_with_register(
        "RegisterComponent(pIBus, &CID_EcoFileSystemManagement1, factory);"
        "\nIdEcoFileSystemManagement1 is generated by the coder."
    )
    assert _id_rule_messages(plan)


def test_spec_mention_outside_new_component_table_does_not_exempt_cid():
    plan = _plan_with_register(
        "RegisterComponent(pIBus, &CID_EcoFileSystemManagement1, factory);"
        "\nReference only: docs/specs/EcoFileSystemManagement1.md"
    )
    assert _id_rule_messages(plan)


def test_cid_system1_not_double_reported_by_id_rule():
    """EcoSystem1 CID usage is handled by its own dedicated rule; the
    Id-header rule must not fire a second, confusing violation for it."""
    plan = _plan_with_register(
        "never do this: &CID_EcoSystem1 in RegisterComponent"
    )
    id_rule = _id_rule_messages(plan)
    assert not any("IdEcoSystem1" in m for m in id_rule)


# ── 2. read(): oversized marketplace-header hint ────────────────────────────
def _read_tool(tmp_path: Path):
    project = tmp_path / "proj"
    marketplace = tmp_path / "marketplace_cache" / "Eco.Math.C89" / "SharedFiles"
    project.mkdir(parents=True)
    marketplace.mkdir(parents=True)
    big_header = marketplace / "IdEcoMathC89.h"
    big_header.write_text(
        "\n".join(f"#define PAD_{i} 0x{i:08X}" for i in range(8000)),
        encoding="utf-8",
    )
    tools = {
        t.name: t
        for t in make_code_search_tools(
            project_dir=project,
            extra_roots=[tmp_path / "marketplace_cache"],
        )
    }
    return tools["read"], big_header


def test_big_marketplace_header_read_gets_grep_hint(tmp_path: Path):
    read, big = _read_tool(tmp_path)
    result = read.execute(read.args_schema.model_validate({
        "path": str(big),
        "limit": 131072,
    }))
    assert "hint:" in result.content
    assert "grep" in result.content


def test_small_read_has_no_grep_hint(tmp_path: Path):
    read, big = _read_tool(tmp_path)
    result = read.execute(read.args_schema.model_validate({
        "path": str(big),
        "limit": 4096,
    }))
    assert "hint:" not in result.content


def test_small_marketplace_header_with_large_limit_has_no_grep_hint(tmp_path: Path):
    read, big = _read_tool(tmp_path)
    small = big.parent / "Small.h"
    small.write_text("#define VALUE 1\n", encoding="utf-8")
    result = read.execute(read.args_schema.model_validate({
        "path": str(small),
        "limit": 131072,
    }))
    assert "hint:" not in result.content


def test_big_project_read_has_no_grep_hint(tmp_path: Path):
    """The hint targets read-only marketplace headers; a big read from
    project_dir (the coder's own sources) is legitimate."""
    project = tmp_path / "proj"
    (project / "src").mkdir(parents=True)
    big_source = project / "src" / "EcoMain.c"
    big_source.write_text(
        "\n".join(f"/* pad {i} */" for i in range(8000)),
        encoding="utf-8",
    )
    marketplace = tmp_path / "marketplace_cache"
    marketplace.mkdir()
    tools = {
        t.name: t
        for t in make_code_search_tools(
            project_dir=project,
            extra_roots=[marketplace],
        )
    }
    read = tools["read"]
    result = read.execute(read.args_schema.model_validate({
        "path": str(big_source),
        "limit": 131072,
    }))
    assert "hint:" not in result.content


# ── 3. auto mode keeps the HITL plan gate ───────────────────────────────────
def test_auto_mode_plan_gate_is_hitl():
    from eco_harness.agent.config.loader import load_config

    config = load_config()
    auto = config.modes.get("auto")
    assert auto is not None, "auto mode missing from modes.yaml"
    assert auto.plan_gate == "hitl", (
        "auto mode must require human plan approval before the coder starts "
        "(user decision 2026-09-08); operators may still opt out per process "
        "with HARNESS_PLAN_GATE=auto_approve"
    )


def test_shared_plan_handoff_validator_rejects_edited_invalid_plan(tmp_path: Path):
    from eco_harness.agent.internal.agents.architect import validate_plan_handoff

    reason = validate_plan_handoff("## Target triple\nLinux", tmp_path)
    assert reason is not None
    assert "Bootstrap chain incomplete" in reason


def _write_trace(path: Path, input_tokens: int, *, cache_reported=None, cache_read=0):
    usage = {"input": input_tokens, "output": 1, "cacheRead": cache_read}
    if cache_reported is not None:
        usage["cacheReadReported"] = cache_reported
    path.write_text(
        json.dumps({"meta": {}, "response": {"usage": usage}}),
        encoding="utf-8",
    )


def test_run_metrics_isolates_sequence_and_unknown_cache_status(tmp_path: Path):
    from eco_harness.backend.server import _collect_run_metrics

    traces = tmp_path / "traces"
    traces.mkdir()
    _write_trace(traces / "001-architect.json", 60000,
                 cache_reported=True, cache_read=0)
    _write_trace(traces / "002-coder.json", 60000)
    _write_trace(traces / "003-tester.json", 60000,
                 cache_reported=True, cache_read=10)

    metrics = _collect_run_metrics(traces, start_sequence=1)
    assert metrics["calls"] == 2
    assert metrics["full_miss_calls"] == 0
    assert metrics["full_miss_tokens"] == 0
    assert metrics["cache_unknown_calls"] == 1
    assert metrics["cache_unknown_tokens"] == 60000


def test_run_metrics_counts_explicit_cache_miss(tmp_path: Path):
    from eco_harness.backend.server import _collect_run_metrics

    traces = tmp_path / "traces"
    traces.mkdir()
    _write_trace(traces / "001-architect.json", 60000,
                 cache_reported=True, cache_read=0)
    metrics = _collect_run_metrics(traces)
    assert metrics["full_miss_calls"] == 1
    assert metrics["full_miss_tokens"] == 60000


def test_trace_error_is_exposed_in_metrics(tmp_path: Path):
    from eco_harness.backend.server import _collect_run_metrics

    metrics = _collect_run_metrics(tmp_path / "traces", trace_errors=["coder trace persistence failed"])
    assert metrics["trace_available"] is False
    assert metrics["trace_errors"] == ["coder trace persistence failed"]
