#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# Eco.AI Harness — native installer (Linux / macOS)
#
# One-command install, no source checkout:
#   curl -fsSL https://downloads.ecoos.dev/eco-harness/install.sh | sh
# or download and run:
#   sh install.sh [--docker] [--update] [--project-dir <dir>]
#
# Native flow: uv installs Python 3.11 if missing → venv at $ECO_HOME/venv →
# wheel from the release manifest → native eco-cli/eco-wizard binaries for the
# target OS (no wine anywhere) → prebuilt RAG index → PATH shims → done.
# Docker flow (--docker): writes a customer docker-compose.yml and starts it.
#
# Missing API keys NEVER block the install: a starter .env with empty values
# is seeded, and the in-app /setup wizard (or manual .env edit) completes it.
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

ECO_HOME="${ECO_HOME:-$HOME/.eco-harness}"
MANIFEST_URL="${ECO_MANIFEST_URL:-https://downloads.ecoos.dev/eco-harness/manifest.json}"
IMAGE_REPO="${ECO_HARNESS_IMAGE:-ghcr.io/peerf-eco/eco.ai}"
PROJECT_DIR_ARG=""
MODE="native"
UPDATE_ONLY=""

usage() { sed -n '2,20p' "$0"; exit 0; }
while [ $# -gt 0 ]; do
  case "$1" in
    --docker) MODE="docker"; shift ;;
    --update) UPDATE_ONLY=1; shift ;;
    --project-dir) PROJECT_DIR_ARG="${2:-}"; shift 2 ;;
    -h|--help) usage ;;
    *) echo "unknown flag: $1" >&2; usage ;;
  esac
done

log() { printf '\033[1;32m[eco-harness]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[eco-harness] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# Single source for the .env seed template (deduped across docker/native).
seed_env() {
  cat > "$1" <<'ENVEOF'
# Eco.AI Harness configuration. The in-app /setup wizard writes here too.
OPENAI_API_KEY=
OPENROUTER_URL=https://openrouter.ai/api/v1
LLM_MODEL=tencent/hy3
EMBEDDINGS_MODEL=qwen/qwen3-embedding-8b
ECO_API_TOKEN=
ENVEOF
  # Seeded before keys exist, but keep it restrictive anyway: the wizard and
  # /rag/token endpoints store real secrets in this file later.
  chmod 600 "$1"
}

# ── OS / arch detection ──────────────────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"
case "$OS" in
  Linux) OS_KEY="linux" ;;
  Darwin) OS_KEY="darwin" ;;
  *) die "unsupported OS: $OS (Windows users: use install.ps1 or --docker)" ;;
esac
case "$ARCH" in
  x86_64|amd64) ARCH_KEY="x86_64" ;;
  aarch64|arm64) ARCH_KEY="arm64" ;;
  *) die "unsupported architecture: $ARCH" ;;
esac
log "detected platform: $OS_KEY/$ARCH_KEY"

command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 ||
  die "need curl or wget to download the installer assets"

fetch() { # fetch <url> <output>
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$1" -o "$2"
  else
    wget -qO "$2" "$1"
  fi
}

sha256_file() { sha256sum "$1" 2>/dev/null | cut -d' ' -f1 || shasum -a 256 "$1" | cut -d' ' -f1; }

# ── Docker mode: compose-only install ────────────────────────────────────────
if [ "$MODE" = "docker" ]; then
  command -v docker >/dev/null 2>&1 || die "docker not found — install Docker first (https://docs.docker.com/get-docker/)"
  mkdir -p "$ECO_HOME"
  PROJECT_DIR="${PROJECT_DIR_ARG:-$HOME/eco-projects/default}"
  mkdir -p "$PROJECT_DIR"
  TMP_TAG_MANIFEST="$(mktemp)"
  IMAGE_TAG=""
  if fetch "$MANIFEST_URL" "$TMP_TAG_MANIFEST" 2>/dev/null; then
    IMAGE_TAG="$(sed -n 's/.*"tag"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$TMP_TAG_MANIFEST" | head -1 || true)"
    # Prefer the manifest's published repo over the compile-time default so
    # the installer always pulls what the release pipeline actually pushed.
    MANIFEST_REPO="$(sed -n 's/.*"repo"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$TMP_TAG_MANIFEST" | head -1 || true)"
    [ -n "$MANIFEST_REPO" ] && IMAGE_REPO="$MANIFEST_REPO"
  else
    log "WARNING: manifest unreachable at $MANIFEST_URL — falling back to $IMAGE_REPO:latest"
  fi
  rm -f "$TMP_TAG_MANIFEST"
  IMAGE_TAG="${IMAGE_TAG:-latest}"
  cat > "$ECO_HOME/docker-compose.yml" <<EOF
# Generated by install.sh — customer Docker install.
# Update:   docker compose -f $ECO_HOME/docker-compose.yml pull && docker compose -f $ECO_HOME/docker-compose.yml up -d
# Project:  change the ECO_PROJECT_DIR host path below to point at another folder.
services:
  eco-harness:
    image: $IMAGE_REPO:$IMAGE_TAG
    container_name: eco-harness
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      ECO_HOME: /data
      ECO_PROJECT_DIR: /project
      ECO_WORKTREE_ROOT: /data/worktrees
      GIT_CONFIG_COUNT: "1"
      GIT_CONFIG_KEY_0: safe.directory
      GIT_CONFIG_VALUE_0: /project
    env_file:
      - $ECO_HOME/.env
    volumes:
      - $ECO_HOME:/data
      - $PROJECT_DIR:/project
    restart: unless-stopped
EOF
  if [ ! -f "$ECO_HOME/.env" ]; then
    seed_env "$ECO_HOME/.env"
  fi
  log "pulling image $IMAGE_REPO:$IMAGE_TAG ..."
  docker compose -f "$ECO_HOME/docker-compose.yml" pull
  docker compose -f "$ECO_HOME/docker-compose.yml" up -d --wait
  # Populate the mounted /data (ECO_HOME) with the native binaries and the
  # prebuilt RAG index from the manifest — the image itself ships neither
  # (keeps the image small and lets `docker compose pull` update them).
  log "downloading binaries + prebuilt RAG index into $ECO_HOME ..."
  if ! docker compose -f "$ECO_HOME/docker-compose.yml" exec -T eco-harness \
      python -m eco_harness update; then
    log "WARNING: in-container download failed — run 'docker compose -f $ECO_HOME/docker-compose.yml exec eco-harness python -m eco_harness update' and check 'python -m eco_harness doctor'"
  fi
  log "Docker install complete."
  log "  UI + API:  http://localhost:8000  (setup wizard at /setup)"
  log "  Config:    $ECO_HOME/.env"
  log "  Update:    docker compose -f $ECO_HOME/docker-compose.yml pull && docker compose -f $ECO_HOME/docker-compose.yml up -d"
  exit 0
fi

if [ -n "$UPDATE_ONLY" ]; then
  [ -x "$ECO_HOME/venv/bin/python" ] || die "no install at $ECO_HOME — run without --update first"
  exec "$ECO_HOME/venv/bin/python" -m eco_harness update
fi

# ── Native flow ──────────────────────────────────────────────────────────────
# 1. uv (provides Python 3.11 automatically)
if ! command -v uv >/dev/null 2>&1; then
  log "installing uv ..."
  if command -v curl >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
  else
    wget -qO- https://astral.sh/uv/install.sh | sh
  fi
  export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
fi
command -v uv >/dev/null 2>&1 || die "uv installation failed"

# 2. venv + wheel
log "creating app venv at $ECO_HOME/venv (Python 3.11 if missing) ..."
uv python install 3.11 >/dev/null 2>&1 || true
uv venv --python 3.11 "$ECO_HOME/venv"
WHEEL_SPEC="eco-harness"
TMP_MANIFEST="$(mktemp)"
if fetch "$MANIFEST_URL" "$TMP_MANIFEST" 2>/dev/null; then
  WHEEL_URL="$(sed -n 's/.*"url"[[:space:]]*:[[:space:]]*"\([^"]*\.whl\)".*/\1/p' "$TMP_MANIFEST" | head -1)"
  [ -n "$WHEEL_URL" ] && WHEEL_SPEC="$WHEEL_URL"
fi
rm -f "$TMP_MANIFEST"
log "installing eco-harness wheel ($WHEEL_SPEC) ..."
uv pip install --python "$ECO_HOME/venv/bin/python" "$WHEEL_SPEC"

# 3. native binaries + prebuilt index from the manifest
log "downloading native binaries + prebuilt RAG index ..."
"$ECO_HOME/venv/bin/python" - "$MANIFEST_URL" <<'PYEOF'
import sys
from eco_harness import update

manifest_url = sys.argv[1]
report = update.run_update(manifest_url)
print(report.summary())
if report.errors:
    raise SystemExit(1)
PYEOF

# 4. seed .env (missing keys never block — /setup or manual edit completes it)
if [ ! -f "$ECO_HOME/.env" ]; then
  seed_env "$ECO_HOME/.env"
  log "seeded $ECO_HOME/.env (empty keys are fine — finish via /setup)"
fi
if [ -n "$PROJECT_DIR_ARG" ]; then
  # Native mode: pre-select the project directory (the UI folder picker can
  # always change it later). ECO_PROJECT_DIR wins over the defaults in
  # paths.project_dir().
  if grep -q "^ECO_PROJECT_DIR=" "$ECO_HOME/.env" 2>/dev/null; then
    sed -i.bak "s|^ECO_PROJECT_DIR=.*|ECO_PROJECT_DIR=$PROJECT_DIR_ARG|" "$ECO_HOME/.env" && rm -f "$ECO_HOME/.env.bak"
  else
    printf '\nECO_PROJECT_DIR=%s\n' "$PROJECT_DIR_ARG" >> "$ECO_HOME/.env"
  fi
  log "project dir: $PROJECT_DIR_ARG"
fi

# 5. PATH shims
SHIM_DIR="$HOME/.local/bin"
mkdir -p "$SHIM_DIR"
cat > "$SHIM_DIR/eco-harness" <<EOF
#!/bin/sh
exec "$ECO_HOME/venv/bin/python" -m eco_harness serve "\$@"
EOF
cat > "$SHIM_DIR/eco-harness-update" <<EOF
#!/bin/sh
exec "$ECO_HOME/venv/bin/python" -m eco_harness update "\$@"
EOF
chmod +x "$SHIM_DIR/eco-harness" "$SHIM_DIR/eco-harness-update"
case ":$PATH:" in
  *":$SHIM_DIR:"*) ;;
  *)
    log "NOTE: $SHIM_DIR is not on your PATH. Add it:"
    log "  echo 'export PATH=\"$SHIM_DIR:\$PATH\"' >> ~/.bashrc  (or your shell profile)"
    ;;
esac

log "install complete."
log "  start:   eco-harness   (or $ECO_HOME/venv/bin/python -m eco_harness serve)"
log "  open:    http://localhost:8000  (setup wizard at /setup — keys optional)"
log "  update:  eco-harness-update   |   uninstall: delete $ECO_HOME and the shims in $SHIM_DIR"
